/* setup database */
alter table if exists orders
    drop constraint if exists fk_orders_customer_customerid;
alter table if exists product_category
    drop constraint if exists fk_productcategory_category_categoryid;
alter table if exists product_category
    drop constraint if exists fk_productcategory_product_productid;
alter table if exists product_order_amount
    drop constraint if exists fk_productorderamount_orders_orderid;
alter table if exists product_order_amount
    drop constraint if exists fk_productorderamount_product_productid;

drop table if exists category cascade;
drop table if exists customer cascade;
drop table if exists orders cascade;
drop table if exists product cascade;
drop table if exists product_category cascade;
drop table if exists product_order_amount cascade;

create table category (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) not null,
    primary key (id)
);
create table customer (
    id int GENERATED BY DEFAULT AS IDENTITY,
    city varchar(255) not null,
    firstName varchar(255) not null,
    houseNumber int not null,
    plz int not null,
    secondName varchar(255) not null,
    street varchar(255) not null,
    primary key (id)
);
create table orders (
    id int GENERATED BY DEFAULT AS IDENTITY,
    creationDate timestamp not null,
    paymentMethod varchar(255) not null,
    customer_id int not null,
    primary key (id)
);
create table product (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) not null,
    price numeric(19, 2) not null,
    primary key (id)
);
create table product_category (
    product_id int not null,
    category_id int not null,
    primary key (product_id, category_id)
);
create table product_order_amount (
    id int GENERATED BY DEFAULT AS IDENTITY,
    amount int not null,
    order_id int not null,
    product_id int not null,
    primary key (id)
);

alter table if exists orders
    add constraint fk_orders_customer_customerid
    foreign key (customer_id)
    references customer;
alter table if exists product_category
    add constraint fk_productcategory_category_categoryid
    foreign key (category_id)
    references category;
alter table if exists product_category
    add constraint fk_productcategory_product_productid
    foreign key (product_id)
    references product;
alter table if exists product_order_amount
    add constraint fk_productorderamount_orders_orderid
    foreign key (order_id)
    references orders;
alter table if exists product_order_amount
    add constraint fk_productorderamount_product_productid
    foreign key (product_id)
    references product;